# name: Deploy healthmap-heart-sayings backend to ECS

# on:
#   push:
#     branches: [master]
#     paths:
#       - '**'
#       - '.github/workflows/deploy-python.yml'

# jobs:
#   deploy:
#     uses: curatimeXai/github-action/.github/workflows/push-backend-to-ecr.yml@master
#     permissions:
#       id-token: write
#       contents: read
#     with:
#       ecr_repository: nightingale/healthmap-heart-sayings
#       cluster_name: nightingale-cluster
#       service_name: nightingale-heart-sayings-API
#       task_definition_name: nightingale-heart-sayings-task
#       build_path: .
      
#       # Optional: add commit SHA as image tag for traceability
#       sha_tag: ${{ github.sha }}
